name: Build ArchISO Stable
on:
  # push:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 0 */7 * *'
  
jobs:
  build:
    env:
      ATHENA_VERSION: 'stable'
      ISO_VERSION: 'rolling' # It must be the same on profiledef.sh and installation_script
      ISO_ARCHITECTURE: 'x86_64'
    runs-on: ubuntu-22.04
    container:
      image: athenaos/base-devel:latest
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Set fastest mirrors
        run: |
          pacman -Syyu --noconfirm reflector
          reflector --age 6 --connection-timeout 15 --download-timeout 15 --latest 21 --fastest 21 --threads 21 --sort rate --protocol https --save /etc/pacman.d/mirrorlist

      - name: Keyrings and Mirrorlists
        run: pacman -Syy --noconfirm archlinux-keyring pacman-mirrorlist athena-keyring athena-mirrorlist blackarch-keyring blackarch-mirrorlist chaotic-keyring chaotic-mirrorlist

      - name: Install dependencies
        run: pacman -Syyu --noconfirm archiso git openssh rsync sshpass wget
          
      - name: Retrieve Athena ISO
        run: git clone https://github.com/Athena-OS/athena-iso
        
      - name: Build ArchISO
        run: |
          cd athena-iso/installation-scripts
          ./30-build-the-iso-the-first-time.sh
          
      - name: Upload to SourceForge
        run: |
          sshpass -p "${{ secrets.SOURCEFORGE_TOKEN }}" rsync -avP -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.md5 $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.sha1 $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.sha256 $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.sha512 ${{ secrets.SOURCEFORGE_USER }}@frs.sourceforge.net:/home/frs/project/athena-iso/${{env.ATHENA_VERSION}}
